name: Deploy_Frontend

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CERTIFICATE_SECRET_FRONTEND }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-13-233-173-196.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
